### ISSUE TITLE
Something went wrong about Pod when pod install 

### ISSUE THREAD

**Issue by AmAdevs** [facebook/facebook-swift-sdk#499] opened 2019-07-30 05:38 UTC
<img width="269" alt="Screen Shot 2562-07-30 at 12 30 39" src="https://user-images.githubusercontent.com/31329764/62103255-12314b80-b2c6-11e9-8ce5-465ee3bc98bc.png">

in Podfile I use

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

then pod install, but in Pods/FacebookShare/ 
it's have only Enums+Extensions.swift. 
not have other pod such as Photo.swift, PhotoShareContent.swift
I want use share photo to facebook.

**Comment by joesus** [comment] 2019-07-31 20:59
The FacebookShare is a lightweight wrapper around the existing FBSDKShareKit. Try checking in there for the files you want to inspect.

**Comment by joesus** [comment] 2019-07-31 21:00
Also this is not a bug so closing for now.

**Closed by joesus** 2019-07-31 21:00 UTC
Labels: bug
