### ISSUE TITLE
<UIAlertController: 0x7fdf80067c00> on <SFAuthenticationViewController: 0x7fdf80860800> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by robertofrontado** [facebook/facebook-swift-sdk#201] opened 2017-11-23 11:15 UTC
Hello guys!, I'm found an issue using `FBSDKGraphRequest`

Specs:
- Swift 4
- Xcode 9.3
- iOS 11.0

Pods:
- FacebookCore (0.3.0)
- FacebookLogin (0.3.0)

So after doing:
```swift
let fbReq = FBSDKGraphRequest(graphPath: "me", parameters: ["fields": "last_name,first_name,email"])
fbReq.start(completionHandler: { (_, result, error) -> Void in
   // Something ...
   showSomeAlertController()
}
```
It throws this error:
```<UIAlertController: 0x7fdf80067c00> on <SFAuthenticationViewController: 0x7fdf80860800> whose view is not in the window hierarchy!```

For some reason `SFAuthenticationViewController` is still alive, its like if the completionHandler is not being called after dismissing `SFAuthenticationViewController` but before/during it

If I add a delay like:
```
DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: {
  showSomeAlertController()
})
```
It works but its just a workaround...

Any ideas?

**Comment by froggomad** [comment] 2018-02-09 05:56
Same issue... thanks for the workaround

**Comment by Sytta** [comment] 2018-04-10 23:32
Great help! Apparently it's not fixed yet.... This workaround came just on the right time!

**Comment by codytwinton** [comment] 2018-07-11 17:36
@robertofrontado - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.

**Comment by DenHeadless** [comment] 2018-07-11 17:49
I believe this is still the issue and is happening on latest Facebook SDK. This is happening not because of FBRequest, but actually because of the login process, that uses SFAuthenticationSession API. When login callbacks are called, SFAuthenticationViewController was not dismissed yet, and still is a current presented controller. Not sure if that's iOS bug or SDK bug, though.

**Comment by codytwinton** [comment] 2018-07-11 18:48
@DenHeadless Thanks for the heads up. I've reopened this issue and assigned the `bug` label. I'll do my best to get to this asap.

In the meantime, if anyone finds more info, please comment on this issue. Also, if anyone finds a fix, please feel free to submit a pull request.

**Comment by robertofrontado** [comment] 2018-07-11 22:17
Yeah indeed this is still an issue

**Comment by codytwinton** [comment] 2018-07-11 22:19
@robertofrontado Thanks for letting us know. I'll do my best to get to this asap.

**Comment by pocketlim** [comment] 2018-07-13 22:02
Can confirm that this is still an issue. Just ran into it today!

**Comment by codytwinton** [comment] 2018-07-13 22:30
Thanks @pocketlim we'll do our best to address this asap.

**Comment by UOCecalero** [comment] 2018-09-20 16:52
Sill having the same issue!

**Comment by robtimp** [comment] 2019-01-04 18:00
@robertofrontado I'm closing as I'm currently unable to reproduce this. If you are still experiencing the issue, please include the contents of `showSomeAlertController()`, because the issue may be there.

**Closed by robtimp** 2019-01-04 18:00 UTC
Labels: bug

**Comment by CobainJosue** [comment] 2019-02-01 05:56
I'm having the same issue with the SDK

 ```
@objc func loginButtonClicked() {
        print("----------------->>>>>>>>>Btn")
        let loginManager = LoginManager()
        loginManager.logIn(readPermissions: [ .publicProfile], viewController: self) { loginResult in
            print("Login result: \(loginResult)")
            switch loginResult {
            case .failed(let error):
                print(error)
            case .cancelled:
                print("User cancelled login.")
            case .success:
                DispatchQueue.main.async {
                    self.performSegue(withIdentifier: "Session", sender: nil)
                }
            }
        }
    }
```

**Comment by Dfmarulanda** [comment] 2019-03-13 15:40
I have the same issue

**Comment by ambrusha** [comment] 2019-07-25 13:34
any updates on this issue?

**Comment by pauloec** [comment] 2019-08-22 18:56
Still happening and it may cause a crash when you try to push modally another view controller to the stack!

**Comment by pauloec** [comment] 2019-08-23 04:31
The issue is that the controller shown to login isn't being dismissed by the login.
When trying to display a new alert on the same view controller this shows up:

`Warning: Attempt to present <UIAlertController: 0x1058c9000>  on <Test.ProfileViewController: 0x10462d260> which is already presenting (null)`

So somehow the reference is lost and the controller isn't showing it but it hasn't fully dismissed the auth session.

@codytwinton @robtimp can someone take a look?
