### ISSUE TITLE
 framework not found Bolts

### ISSUE THREAD

**Issue by hemanthBusi** [facebook/facebook-swift-sdk#501] opened 2019-08-06 07:25 UTC
Hi, 
I updated  FBSDKCoreKit, FacebookCore, FacebookLogin, FacebookShare to latest versions 
now i'm facing issue as framework not found Bolts i'm using pod version 1.7.2

**Comment by levibostian** [comment] 2019-08-07 20:45
Yup. Same error for me. [Bolts was removed](https://github.com/facebook/facebook-swift-sdk/commit/ef89eb8d48908d80dd111d05dc6317bb8d923d29) from the project. 

I manually added it back in to fix this issue. 
```
facebookVersion = "0.8.0"
pod 'FacebookCore', "~> #{facebookVersion}"
pod 'FacebookLogin', "~> #{facebookVersion}"
pod 'FacebookShare', "~> #{facebookVersion}"
pod 'Bolts', "~> 1.9.0"
```

**Comment by joesus** [comment] 2019-08-09 19:13
Closing as this was an intentional deprecation and not a bug.

**Closed by joesus** 2019-08-09 19:13 UTC
Labels: bug
